apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      imagePullSecrets:
        - name: cubelgrg
      containers:
      - name: auth-portal
        image: cubelgregistry.azurecr.io/cubelogin/api-demo:latest
        ports:
        - containerPort: 8080
        name : api-demo