# logback configuration
logging:
  level:
   org.springframework.web: INFO
   com.aircuve: DEBUG
  file: logs/spring-boot-logging.log

  
---

spring.profiles: logging-daily
logging:
  config: classpath:logback.xml
---
spring.profiles: logging-info
logging:
  file: logs/application.log
  level:
    org.thymeleaf: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.quartz.core: INFO
    org.h2.server.web: INFO
--- 
server:
  port: 8080